# Generated by Django 4.1.13 on 2024-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
