# Generated by Django 5.0.1 on 2024-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_remove_home_first_name_remove_home_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
