# Generated by Django 5.0.1 on 2024-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0003_alter_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume',
            field=models.FileField(default='Anupama_Ellath_CV.pdf', upload_to='picture/'),
        ),
    ]
